Repository onebeyond/license-checker, pull requests merged in 2021-11, with the labels that each got.

#34 v1.1.0
  .github/workflows/npm-publish.yml
  CHANGELOG.md
  package-lock.json
  package.json
  src/utils.js
Labels: enhancement

#35 Is ci
  CHANGELOG.md
  package-lock.json
  package.json
Labels: bug

#31 fix: license validation
  index.js
  src/utils.js
Labels: hacktoberfest-accepted

#36 Publish action
  .github/workflows/npm-publish.yml
  CHANGELOG.md
  package-lock.json
  package.json
  src/utils.js
Labels: bug, enhancement
